<?php

namespace Tests\Feature;

use Illuminate\Database\QueryException;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class TransactionTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        DB::delete('delete from categories');
    }

    public function testTransactionSuccess(): void
    {
        DB::transaction(function () {
            DB::insert('insert into categories (id, name, description, created_at) values (?, ?, ?, ?)', [
                "GADGET", "Gadget", "Gadget Category", "2024-01-01 00:00:00"
            ]);
            DB::insert('insert into categories (id, name, description, created_at) values (?, ?, ?, ?)', [
                "FOOD", "Food", "Food Category", "2024-01-01 00:00:00"
            ]);
        });

        $result = DB::select('select * from categories');
        $this->assertCount(2, $result);
    }

    public function testTransactionFailed(): void
    {
        try {
            DB::transaction(function () {
                DB::insert('insert into categories (id, name, description, created_at) values (?, ?, ?, ?)', [
                    "GADGET", "Gadget", "Gadget Category", "2024-01-01 00:00:00"
                ]);
                DB::insert('insert into categories (id, name, description, created_at) values (?, ?, ?, ?)', [
                    "GADGET", "Food", "Food Category", "2024-01-01 00:00:00"
                ]);
            });
        } catch (QueryException $error) {
            // expected exception
        }

        $result = DB::select('select * from categories');
        $this->assertCount(0, $result);
    }

    public function testManualTransactionSuccess(): void
    {
        try {
            DB::beginTransaction();
            DB::insert('insert into categories (id, name, description, created_at) values (?, ?, ?, ?)', [
                "GADGET", "Gadget", "Gadget Category", "2024-01-01 00:00:00"
            ]);
            DB::insert('insert into categories (id, name, description, created_at) values (?, ?, ?, ?)', [
                "Food", "Gadget", "Gadget Category", "2024-01-01 00:00:00"
            ]);
            DB::commit();
        } catch (QueryException $error) {
            DB::rollback();
        }

        $result = DB::select('select * from categories');
        $this->assertCount(2, $result);
    }
    public function testManualTransactionFailed(): void
    {
        try {
            DB::beginTransaction();
            DB::insert('insert into categories (id, name, description, created_at) values (?, ?, ?, ?)', [
                "GADGET", "Gadget", "Gadget Category", "2024-01-01 00:00:00"
            ]);
            DB::insert('insert into categories (id, name, description, created_at) values (?, ?, ?, ?)', [
                "GADGET", "Gadget", "Gadget Category", "2024-01-01 00:00:00"
            ]);
            DB::commit();
        } catch (QueryException $error) {
            DB::rollback();
        }

        $result = DB::select('select * from categories');
        $this->assertCount(0, $result);
    }
}
